### ISSUE TITLE
Usage and how to setup?

### ISSUE THREAD

**Issue by timothymunyao** [jeffThompson/TCPDUMP#1]
Which version of python have you used? Can't import settings

**Comment by jeffThompson** [comment]
Python 2.7, I would guess (it's been a while)

**Comment by walimorris** [comment]
Hey Jeff. First off, really cool project you have here. I'm a new CS student and am interested in learning a bit more about Linux and TCP so I decided the best way was to try out a program. Even though this is in Python 2.7, it's really cool to see your work. I was wondering how you were able to make such a neat retro GUI. Could you lead me to some resources I can study to incorporate something like this in my project? Thanks a bunch and again, really like your work.

**Comment by jeffThompson** [comment]
@walimorris – thanks for the kind words! Do you mean the GUI on the website or in the Terminal?

**Comment by walimorris** [comment]
@jeffThompson The terminal, although your website is awesome as well.  I studied your code a bit and found some great resources to implement the same idea using Python3. I Seriously appreciate this program, your code gave me insight on some features I wanted, as I want my program to run from the command line and wanted to spruce it up a bit.

**Comment by jeffThompson** [comment]
@walimorris – aha yes! Shouldn't take too much to make the Terminal stuff work in Python 3. Mostly it's color and bold commands, plus some other formatting stuff. Honestly, it mostly came from lots of experimentation! Closing this issue, but feel free to message me if you have other questions.
